-- Instruction Set Reference:
-- Opcode | Mnemonic | Description
-- ----------------------------
-- 0x00   | LDI    | Load immediate value into register
-- 0x01   | LD     | Load from memory into register
-- 0x02   | STORE  | Store register to memory
-- 0x03   | ADD    | Add memory to register
-- 0x04   | SUB    | Subtract memory from register
-- 0x05   | OR     | Bitwise OR with memory
-- 0x06   | LSR    | Logical shift right register
-- 0x07   | CMP    | Compare register with memory
-- 0x08   | BRA    | Branch always to address
-- 0x09   | BEQ    | Branch if Z=1
-- 0x0A   | AND    | Bitwise AND memory with register
-- 0x0B   | BPL    | Branch if N=0
-- 0x0C   | KEY0   | Read key input from player 0
-- 0x0D   | PLAY   | Play piezo sound
-- 0x0E   | BUA    | Branch if UART has data
-- 0x0F   | KEY1   | Read key input from player 1

(
   x"1089",
   x"E100",
   x"007D",
   x"8100",
   x"0001",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"FFFF",
   x"1C8A",
   x"1B00",
   x"788C",
   x"9100",
   x"0000",
   x"2889",
   x"308B",
   x"2089",
   x"E100",
   x"007D",
   x"8100",
   x"0085",
   x"0000",
   x"8001",
   x"0001",
   x"FFFF",
   x"FFFF"
);