# Files in the project. Make sure the first file is the top module
VHD = uprogCPU.vhd mem/uMem.vhd mem/pMem.vhd kbd/kbd_enc.vhd kbd/kbd_mngr.vhd K1.vhd K2.vhd Piezo.vhd GRx.vhd vga/vga_motor.vhd vga/tile_rom.vhd

# Design constraints file
XDC = Basys3.xdc

# Testbench file
TBF = uprogCPU_tb.vhd

# Include Makefile utilities
include /courses/TSEA83/bin/util.mk



